### PR TITLE
[feature] wifi icon dynamically shows wifi strength

### PR DESCRIPTION
**Pull request by kopp4**
# Description

Added a feature that wifi icon shows wifi signal strength, deleted wifi script and integrated wifi name feature into eww.
**script/wifi has been deleted**
**Using new icons which are as follows**
```
:strength WLAN_ICON :offline "󰤮" :excellent "󰤨" :good "󰤥" :okay "󰤢" :slow "󰤟")
```
image

***Source code is originally from [here](https://dharmx.is-a.dev/eww-powermenu/#full-code)***

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

> P.S. First time pulling a request(plz forget my last mistake ; ;), please forgive and tell me if I've done anything wrong..

### CODE REVIEW

**Comment by kopp4** [comment]
It might be not really practical tho, hope you like it....

**Comment by AmadeusWM** [comment]
Looks good! I will merge.

**Comment by AmadeusWM** [comment]
Are the wifi icons small for you as well now? Might have to increase the font-size then.
image

**Comment by kopp4** [comment]
> 
It’s actually not, probably because of my font. Thanks a lot anyway<3<3

**Pull request merged**
